import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiFlutter,
  SiExpo,
  SiFirebase,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiGit,
  SiNpm,
  SiFigma,
  SiAndroidstudio,
  SiPython,
  SiCplusplus,
} from "react-icons/si";

export const skills = [
  { icon: SiReact, label: "React.js", color: "#61DAFB", category: "Frontend" },
  {
    icon: SiReact,
    label: "React Native",
    color: "#61DAFB",
    category: "Mobile",
  },
  {
    icon: SiNextdotjs,
    label: "Next.js",
    color: "#000000",
    category: "Frontend",
  },
  {
    icon: SiTailwindcss,
    label: "Tailwind CSS",
    color: "#38BDF8",
    category: "Frontend",
  },
  {
    icon: SiTypescript,
    label: "TypeScript",
    color: "#3178C6",
    category: "Language",
  },
  {
    icon: SiJavascript,
    label: "JavaScript",
    color: "#F7DF1E",
    category: "Language",
  },
  { icon: SiHtml5, label: "HTML", color: "#E34F26", category: "Frontend" },
  { icon: SiCss3, label: "CSS", color: "#1572B6", category: "Frontend" },
  { icon: SiFlutter, label: "Flutter", color: "#02569B", category: "Mobile" },
  { icon: SiExpo, label: "Expo", color: "#000020", category: "Mobile" },
  {
    icon: SiFirebase,
    label: "Firebase",
    color: "#FFCA28",
    category: "Backend",
  },
  { icon: SiMongodb, label: "MongoDB", color: "#47A248", category: "Database" },
  { icon: SiMysql, label: "SQL", color: "#00758F", category: "Database" },
  {
    icon: SiNodedotjs,
    label: "Node.js",
    color: "#339933",
    category: "Backend",
  },
  { icon: SiGit, label: "Git", color: "#F05032", category: "Tools" },
  { icon: SiNpm, label: "npm", color: "#CB3837", category: "Tools" },
  { icon: SiFigma, label: "Figma", color: "#F24E1E", category: "Design" },
  {
    icon: SiAndroidstudio,
    label: "Android Studio",
    color: "#3DDC84",
    category: "Tools",
  },
  { icon: SiPython, label: "Python", color: "#3776AB", category: "Language" },
  { icon: SiCplusplus, label: "C++", color: "#00599C", category: "Language" },
];

export const categories = [
  "All",
  "Frontend",
  "Backend",
  "Mobile",
  "Language",
  "Database",
  "Tools",
  "Design",
];
